### ISSUE TITLE
Set changed size during iteration

### ISSUE THREAD

**Issue by TD22057** [xmikos/signaller#1]
I'm trying to use this library for a loose coupling problem with some network code.  In this case, there is manager/child relationship.  The child gets added to the manager which uses signals to connect callbacks into itself.  When the child closes, the manager needs to be notified.   When that happens the manager will disconnect itself from the child.

The problem is that using set() for the _slots variable means this isn't possible.  Because the slot calls disconnect which changes the size of the slots and triggers the error.  

```python
import signaller

class Manager:
    def __init__(self):
        self.children = []
        
    def add(self, child):
        self.children.append(child)
        child.closing.connect(self.remove)

    def remove(self,child):
        self.children.remove(child)
        child.closing.disconnect(self.remove)

class Child:
    def __init__(self):
        self.closing = signaller.Signal("closing")

    def close(self):
        self.closing.emit(self)

mgr = Manager()
child = Child()
mgr.add(child)
child.close()
```

which yields:
```
Traceback (most recent call last):
  File "bug.py", line 25, in <module>
    child.close()
  File "bug.py", line 20, in close
    self.closing.emit(self)
  File "/home/ted/miniconda3/envs/devenv/lib/python3.6/site-packages/signaller.py", line 107, in emit
    for ref in self._slots:
RuntimeError: Set changed size during iteration
```

At least for me, this is common use case that I've encountered in several systems I've built (usually network related).  There are several ways that it could be supported: not using set (use list and iterate backwards), making a copy of the set before calling, etc.

**Comment by TD22057** [comment]
This isn't the best way to solve this problem, but to give you an idea of what I mean, if emit loops over the slots using an index in reverse order, it's immune to changes in the slots during iteration:

```
    def emit(self, *args, **kwargs):
        #ORIG: for ref in self._slots:
        slots = list(self._slots)
        for i in reversed(range(len(sl))):
            ref = slots[i]
```
